/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.CustomerDAO;
import com.essar.dao.DayBookDAO;
import com.essar.dao.IncomeExpenseDAO;
import com.essar.dao.PricingTierDAO;
import com.essar.dao.ProductCategoryDAO;
import com.essar.pojos.Customer;
import com.essar.pojos.DayBook;
import com.essar.pojos.IncomeExpense;
import com.essar.pojos.PricingTier;
import com.essar.utils.TableMouseListener;
import com.essar.pojos.ProductCategory;
import com.essar.utils.GenericUtils;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rahumathulla
 */
public class DayBookForm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ProductCategory
     */
    long dayBookid=0;
    DefaultTableModel dayBookModel = null;
    DecimalFormat df = new DecimalFormat("##,##,###.##");
    public DayBookForm() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        mnuCustomer = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mitDelete = new javax.swing.JMenuItem();
        mitEdit = new javax.swing.JMenuItem();
        pnlDayBook = new javax.swing.JPanel();
        panDayBook = new javax.swing.JScrollPane();
        tblDayBook = new javax.swing.JTable();
        lblTotalCredit = new javax.swing.JLabel();
        lblTotalDebit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBalance = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblParticularName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        txtAmount = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();
        cmbParticularName = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        dtpEventDate = new com.toedter.calendar.JDateChooser();
        lblAmount = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        mitDelete.setText("jMenuItem1");

        mitEdit.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Day Book");
        setExtendedState(6);
        setName("frmProductCategory"); // NOI18N

        tblDayBook.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        tblDayBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Particular Name", "Debit", "Credit", "Remarks", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panDayBook.setViewportView(tblDayBook);

        lblTotalCredit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCredit.setForeground(new java.awt.Color(0, 102, 0));
        lblTotalCredit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCredit.setText("Cr Total");

        lblTotalDebit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalDebit.setForeground(new java.awt.Color(204, 0, 0));
        lblTotalDebit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalDebit.setText("Dr Total");

        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(0, 102, 204));
        lblBalance.setText("Balance: ");

        javax.swing.GroupLayout pnlDayBookLayout = new javax.swing.GroupLayout(pnlDayBook);
        pnlDayBook.setLayout(pnlDayBookLayout);
        pnlDayBookLayout.setHorizontalGroup(
            pnlDayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDayBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDayBookLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(552, 552, 552))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDayBookLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(pnlDayBookLayout.createSequentialGroup()
                        .addComponent(panDayBook, javax.swing.GroupLayout.PREFERRED_SIZE, 1326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlDayBookLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(lblBalance)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDayBookLayout.setVerticalGroup(
            pnlDayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDayBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panDayBook, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBalance)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCustomerName.setText("Date");

        lblParticularName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblParticularName.setText("Particular Name");

        lblAddress.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblAddress.setText("Remarks");

        txtRemarks.setColumns(16);
        txtRemarks.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtRemarks.setRows(3);
        txtRemarks.setTabSize(2);
        txtRemarks.setToolTipText("");
        txtRemarks.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtRemarks);

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblCount.setForeground(new java.awt.Color(102, 102, 255));
        lblCount.setText("Count:");

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        dtpEventDate.setDateFormatString("dd/MM/yyyy");

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAmount.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDayBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblParticularName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbParticularName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtpEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addGap(6, 6, 6)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblParticularName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cmbParticularName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(dtpEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblCount))
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(pnlDayBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(btnSave.getText().equalsIgnoreCase("add")){
            
            IncomeExpenseDAO incomeExpenseDAO = new IncomeExpenseDAO();
            renderParticularsDataIntoDropDown(incomeExpenseDAO.retrieveAll());
            btnSave.setText("Save");
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png")));
            enableFormElements(true);
            dtpEventDate.setDate(new Date());
            txtAmount.requestFocus();
        }else{
            if(validateForm()){
                if(dayBookid>0)
                    updateDayBookForm();
                else
                    saveDayBookForm();
                initializeForm();

            }   

        }
    }//GEN-LAST:event_btnSaveActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DayBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DayBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DayBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DayBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</etxtRemarks>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</etxtRemarks>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</etxtRemarks>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</etxtRemarks>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DayBookForm().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        DefaultTableModel model = (DefaultTableModel) tblDayBook.getModel();
        model.setRowCount(0);
        
        btnSave.setText("Add");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png")));
        btnSave.requestFocus();
        txtAmount.setText("");
        //txtCustomerPhone.setText("");
        txtRemarks.setText("");
        cmbParticularName.removeAllItems();
        //tblProductCategory.re();
        //tblCategory.remove(panPricingTier);
        enableFormElements(false);
        DayBookDAO dayBookDAO = new DayBookDAO();
        renderDataIntoTable(dayBookDAO.retrieveAll());
        mnuCustomer = new JPopupMenu();
        
        mitEdit = new JMenuItem("Edit");
        mitEdit.addActionListener(this);
        
        mitDelete = new JMenuItem("Delete");
        mitDelete.addActionListener(this);
        
        mnuCustomer.add(mitEdit);
        mnuCustomer.add(mitDelete);
         // sets the popup menu for the table
        tblDayBook.setComponentPopupMenu(mnuCustomer);      
        tblDayBook.addMouseListener(new TableMouseListener(tblDayBook));
        
        TableColumn idColumn1 = tblDayBook.getColumnModel().getColumn(tblDayBook.getColumnCount()-1);
        idColumn1.setPreferredWidth(0);
        idColumn1.setMinWidth(0);
        idColumn1.setMaxWidth(0);
        
        TableColumn remarksColumn = tblDayBook.getColumnModel().getColumn(tblDayBook.getColumnCount()-2);
        remarksColumn.setPreferredWidth(500);
        remarksColumn.setMinWidth(500);
        //remarksColumn.setMaxWidth(500);
        
        TableColumn itemNameColumn = tblDayBook.getColumnModel().getColumn(1);
        itemNameColumn.setPreferredWidth(400);
        itemNameColumn.setMinWidth(400);
        //itemNameColumn.setMaxWidth(400);
        
        /*TableColumn drColumn = tblDayBook.getColumnModel().getColumn(1);
        itemNameColumn.setPreferredWidth(240);
        itemNameColumn.setMinWidth(240);
        itemNameColumn.setMaxWidth(240);*/
        
        //TableColumn drColumn = tblDayBook.getColumnModel().getColumn(2);

        //TableColumn crColumn = tblDayBook.getColumnModel().getColumn(3);
        
        dayBookid = 0;
    }
    
    public void enableFormElements(boolean flag){
        txtAmount.setEnabled(flag);
        dtpEventDate.setEnabled(flag);
        cmbParticularName.setEnabled(flag);
        txtRemarks.setEnabled(flag); 
    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        if(null == cmbParticularName.getSelectedItem()){
            JOptionPane.showMessageDialog(null, "Please select particular name.");
            cmbParticularName.requestFocus();
            return false;
        }
        
        if(null == dtpEventDate.getDate()){
            JOptionPane.showMessageDialog(null, "Please select a date.");
            dtpEventDate.requestFocus();
            return false;
        }
        
        if(null == txtAmount.getText() || "".equalsIgnoreCase(txtAmount.getText().trim()) || !(txtAmount.getText().matches("-?(\\d*\\.)?\\d+"))){
            JOptionPane.showMessageDialog(null, "Amount value "+txtAmount.getText() +" is not valid.");
            txtAmount.requestFocus();
            return false;
        }
        
        
        
        
               
        //txtProductCategoryName.setText("");
        return true;
    }
    
    public void saveDayBookForm(){
 
        DayBook dayBook = new DayBook();
        dayBook.setIncomeExpenseId(((IncomeExpense)cmbParticularName.getSelectedItem()).getIncomeExpenseId());
        dayBook.setEventDate(dtpEventDate.getDate());
        dayBook.setParticularName(cmbParticularName.getSelectedItem().toString());
        dayBook.setType(((IncomeExpense)cmbParticularName.getSelectedItem()).getType());
        if(((IncomeExpense)cmbParticularName.getSelectedItem()).getType().equalsIgnoreCase("credit")){
            dayBook.setCreditAmount(Double.parseDouble(txtAmount.getText().trim()));
        }else{
            dayBook.setDebitAmount(Double.parseDouble(txtAmount.getText().trim()));
        }
        
        dayBook.setRemarks(txtRemarks.getText());
        DayBookDAO dayBookDAO = new DayBookDAO();
        dayBookDAO.insertIntoDB(dayBook);
        
    }
    public void updateDayBookForm(){
 
        DayBook dayBook = new DayBook();
        dayBook.setDayBookId(dayBookid);
        dayBook.setIncomeExpenseId(((IncomeExpense)cmbParticularName.getSelectedItem()).getIncomeExpenseId());
        dayBook.setEventDate(dtpEventDate.getDate());
        dayBook.setParticularName(cmbParticularName.getSelectedItem().toString());
        dayBook.setType(((IncomeExpense)cmbParticularName.getSelectedItem()).getType());
        if(((IncomeExpense)cmbParticularName.getSelectedItem()).getType().equalsIgnoreCase("credit")){
            dayBook.setCreditAmount(Double.parseDouble(txtAmount.getText().trim()));
            dayBook.setDebitAmount(0);
        }else{
            dayBook.setDebitAmount(Double.parseDouble(txtAmount.getText().trim()));
            dayBook.setCreditAmount(0);
        }
        
        dayBook.setRemarks(txtRemarks.getText());
        DayBookDAO dayBookDAO = new DayBookDAO();
        dayBookDAO.updateRecord(dayBook);
        
        //IncomeExpenseDAO incomeExpenseDAO = new IncomeExpenseDAO();
        //incomeExpenseDAO.updateRecord(incomeExpense);
        
    }
    
    public void renderParticularsDataIntoDropDown(List<IncomeExpense> incomeExpenseList){
        IncomeExpense incomeExpense = null;
        cmbParticularName.removeAllItems();
        if(incomeExpenseList!= null){
            for(int i=0; i<incomeExpenseList.size();i++){
                cmbParticularName.addItem(incomeExpenseList.get(i));
            }
            cmbParticularName.setSelectedIndex(0);
            //incomeExpense = (IncomeExpense)cmbParticularName.getSelectedItem();            
        }
    }
    public void renderDataIntoTable(List<DayBook> dayBookList){
        
        tblDayBook.removeAll();
        tblDayBook.repaint();
        DefaultTableModel model = (DefaultTableModel) tblDayBook.getModel();
        model.setRowCount(0);
        
        dayBookModel = (DefaultTableModel) tblDayBook.getModel();
        TableColumn column = tblDayBook.getColumnModel().getColumn(tblDayBook.getColumnCount()-1);
        column.setMaxWidth(0);
        column.setWidth(0);
        column.setPreferredWidth(0);
        lblCount.setText("Count : "+dayBookList.size());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        //pricingTierModel.getColumnName(3).
        //System.out.println("-----"+pricingTierList.size());
        double totalDebit =0;
        double totalCredit=0;
        for(int i=0;i<dayBookList.size();i++){
            dayBookModel.addRow(new Object[]{sdf.format(dayBookList.get(i).getEventDate()),dayBookList.get(i).getParticularName(),dayBookList.get(i).getDebitAmount(),dayBookList.get(i).getCreditAmount(), dayBookList.get(i).getRemarks(), dayBookList.get(i).getDayBookId()});
            totalCredit = totalCredit + dayBookList.get(i).getCreditAmount();
            totalDebit = totalDebit + dayBookList.get(i).getDebitAmount();
        //model.
        }        
        lblTotalCredit.setText(df.format(totalCredit));
        lblTotalDebit.setText(df.format(totalDebit));
        lblBalance.setText("Balance : "+df.format((totalCredit-totalDebit))+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbParticularName;
    private com.toedter.calendar.JDateChooser dtpEventDate;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblParticularName;
    private javax.swing.JLabel lblTotalCredit;
    private javax.swing.JLabel lblTotalDebit;
    private javax.swing.JMenuItem mitDelete;
    private javax.swing.JMenuItem mitEdit;
    private javax.swing.JPopupMenu mnuCustomer;
    private javax.swing.JScrollPane panDayBook;
    private javax.swing.JPanel pnlDayBook;
    private javax.swing.JTable tblDayBook;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtRemarks;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();
            if (menu == mitDelete) {
              //txtParticularName= tblIncomeExpense.getSelectedRow();
                System.out.println("--------INSIDE DELETE-"+tblDayBook.getModel().getValueAt(tblDayBook.getSelectedRow(),0));
                String dayBookId = tblDayBook.getModel().getValueAt(tblDayBook.getSelectedRow(),tblDayBook.getColumnCount()-1).toString();
                long id = Long.parseLong(dayBookId);
                DayBookDAO dayBookDAO = new DayBookDAO();
                dayBookDAO.deleteRecordById(id);
                GenericUtils.removeRowFromJTable(tblDayBook, dayBookModel);
            }
            if (menu == mitEdit) {
                //int rowIndex = tblSupplier.getSelectedRow();
                enableFormElements(true);
                DayBook dayBook = null;
                System.out.println("--------INSIDE Edit-"+tblDayBook.getModel().getValueAt(tblDayBook.getSelectedRow(),1));
                dayBookid = Integer.parseInt(tblDayBook.getModel().getValueAt(tblDayBook.getSelectedRow(),tblDayBook.getColumnCount()-1).toString());
                DayBookDAO dayBookDAO = new DayBookDAO();
                dayBook = dayBookDAO.retrieveById(dayBookid);
                System.out.println("--"+dayBook.getParticularName());
                //txtAmount.setText(dayBook.getIncomeExpenseName());
                
                //=========Retrieving all Particulars and setting the appropriated one as selected.
                IncomeExpenseDAO incomeExpenseDAO =  new IncomeExpenseDAO();
                List<IncomeExpense> incomeExpenseList = incomeExpenseDAO.retrieveAll();
                renderParticularsDataIntoDropDown(incomeExpenseList);
                for(int i=0;i<incomeExpenseList.size();i++){
                    if(dayBook.getIncomeExpenseId()==incomeExpenseList.get(i).getIncomeExpenseId()){
                        cmbParticularName.setSelectedItem(incomeExpenseList.get(i));
                    }
                }
                //**************
                dtpEventDate.setDate(dayBook.getEventDate());
                if(dayBook.getCreditAmount()>0)
                    txtAmount.setText(dayBook.getCreditAmount()+"");
                else
                    txtAmount.setText(dayBook.getDebitAmount()+"");
                txtRemarks.setText(dayBook.getRemarks());
                
                //btnSave.setText("Save");
                //btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png")));
                btnSave.setText("Update");
                btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png")));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
}
