/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.GstDAO;
import com.essar.dao.PricingTierDAO;
import com.essar.dao.StockDAO;
import com.essar.dao.SupplierDAO;
import com.essar.pojos.GST;
import com.essar.pojos.Sales;
import com.essar.pojos.SalesDetails;
import com.essar.utils.ConnectionManager;
import com.essar.utils.TableMouseListener;
import com.essar.pojos.Stock;
import com.essar.pojos.Supplier;
import com.essar.suggestion.StockListingForSales_Vp;
import com.essar.suggestion.SuggestionExampleMain;
import com.essar.utils.QueryStrings;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rahumathulla
 */
public class StockTransfer extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Stock
     */
    long stockIdEdit=0;
    DecimalFormat df = new DecimalFormat("####.##");
    Stock stock = null;
    double gSalesPercentage = 0;
    double gStockAvailable = 0;
    public StockTransfer() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStockEntry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblQtyTrfr = new javax.swing.JLabel();
        txtHSNCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtGstPercentage = new javax.swing.JTextField();
        txtGstAmount = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        lblUnitPrice3 = new javax.swing.JLabel();
        lblUnitPrice2 = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblAvailableQty = new javax.swing.JLabel();
        txtQtyToTransfer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTarget = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbSource = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        cmdTransfer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Transfer");

        pnlStockEntry.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));
        pnlStockEntry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("HSN Code");
        pnlStockEntry.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 27, 118, 22));

        lblQtyTrfr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQtyTrfr.setText("Quantity to be transferred");
        pnlStockEntry.add(lblQtyTrfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 133, 163, 22));

        txtHSNCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHSNCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHSNCodeActionPerformed(evt);
            }
        });
        txtHSNCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHSNCodeKeyPressed(evt);
            }
        });
        pnlStockEntry.add(txtHSNCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 28, 140, -1));

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemNameMouseClicked(evt);
            }
        });
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemNameKeyTyped(evt);
            }
        });
        pnlStockEntry.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 61, 184, -1));

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUnitPrice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        pnlStockEntry.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 54, 62, -1));

        txtGstPercentage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGstPercentage.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGstPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGstPercentageActionPerformed(evt);
            }
        });
        pnlStockEntry.add(txtGstPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 81, 62, -1));

        txtGstAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGstAmount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGstAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGstAmountActionPerformed(evt);
            }
        });
        pnlStockEntry.add(txtGstAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 108, 62, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantity.setText("Quantity");
        pnlStockEntry.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 140, 111, -1));

        lblUnitPrice3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice3.setText("GST Amt");
        pnlStockEntry.add(lblUnitPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 111, 118, -1));

        lblUnitPrice2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice2.setText("GST%");
        pnlStockEntry.add(lblUnitPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 84, 104, -1));

        lblUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice.setText("Unit Price");
        pnlStockEntry.add(lblUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 55, 62, -1));

        lblAvailableQty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailableQty.setForeground(new java.awt.Color(0, 102, 0));
        lblAvailableQty.setText("00");
        pnlStockEntry.add(lblAvailableQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 140, 52, -1));

        txtQtyToTransfer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQtyToTransfer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyToTransferFocusLost(evt);
            }
        });
        txtQtyToTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtyToTransferMouseClicked(evt);
            }
        });
        txtQtyToTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyToTransferActionPerformed(evt);
            }
        });
        txtQtyToTransfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyToTransferKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyToTransferKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyToTransferKeyTyped(evt);
            }
        });
        pnlStockEntry.add(txtQtyToTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 133, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Commodity/Item Name");
        pnlStockEntry.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 135, 22));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Traget ");
        pnlStockEntry.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, 135, 22));

        cmbTarget.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTarget.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thalavila", "Vamanapuram" }));
        cmbTarget.setSelectedIndex(1);
        cmbTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbTargetKeyPressed(evt);
            }
        });
        pnlStockEntry.add(cmbTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 94, 184, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Source");
        pnlStockEntry.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 135, 22));

        cmbSource.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thalavila", "Vamanapuram" }));
        cmbSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSourceActionPerformed(evt);
            }
        });
        cmbSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSourceKeyPressed(evt);
            }
        });
        pnlStockEntry.add(cmbSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 27, 184, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmdTransfer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_small.png"))); // NOI18N
        cmdTransfer.setText("Transfer");
        cmdTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStockEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHSNCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHSNCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtItemName.requestFocus();
        }
    }//GEN-LAST:event_txtHSNCodeKeyPressed

    private void txtHSNCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHSNCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHSNCodeActionPerformed

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtItemNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemNameMouseClicked

    }//GEN-LAST:event_txtItemNameMouseClicked

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
        System.out.println("---inside Action Peformed");
        performItemFieldAction();
        
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            System.out.println("---inside item name enter");
            try{
                performItemFieldAction();
            }
            catch(Exception e){
                System.out.println("Error Retrieving the item -"+e.getMessage());
            }
        }
    }//GEN-LAST:event_txtItemNameKeyReleased

    private void txtItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameKeyTyped

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtGstPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGstPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGstPercentageActionPerformed

    private void txtGstAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGstAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGstAmountActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmdTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTransferActionPerformed
        // TODO add your handling code here:
        //initializeForm();
        if(validateForm()){
            JOptionPane.showMessageDialog(this, "All conditions met.");
        }
    }//GEN-LAST:event_cmdTransferActionPerformed

    private void txtQtyToTransferFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyToTransferFocusLost
        // TODO add your handling code here:
        validateForm();
    }//GEN-LAST:event_txtQtyToTransferFocusLost

    private void txtQtyToTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtyToTransferMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyToTransferMouseClicked

    private void txtQtyToTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyToTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyToTransferActionPerformed

    private void txtQtyToTransferKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyToTransferKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyToTransferKeyPressed

    private void txtQtyToTransferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyToTransferKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyToTransferKeyReleased

    private void txtQtyToTransferKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyToTransferKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyToTransferKeyTyped

    private void cmbTargetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTargetKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            //cmbSupplier.requestFocus();
            
        }
    }//GEN-LAST:event_cmbTargetKeyPressed

    private void cmbSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSourceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSourceKeyPressed

    private void cmbSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSourceActionPerformed
        // TODO add your handling code here:
        if("Thalavila".equalsIgnoreCase(cmbSource.getSelectedItem().toString())){
            //clearItemFields();
            System.out.println("T----------");
            SuggestionExampleMain.populateItemNames(this, txtItemName);
            txtItemName.requestFocus();
            
        }else if("Vamanapuram".equalsIgnoreCase(cmbSource.getSelectedItem().toString())){
            System.out.println("V----------");
            txtItemName.removeAll();
            StockListingForSales_Vp.populateItemNames(this, txtItemName);
            txtItemName.requestFocus();
        }
    }//GEN-LAST:event_cmbSourceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockTransfer().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        stockIdEdit =0;
        txtHSNCode.requestFocus();

        SupplierDAO supplierDAO = new SupplierDAO();
        renderDataIntoTable(supplierDAO.retrieveAll());
        SuggestionExampleMain.populateItemNames(this, txtItemName);
            //txtItemName.requestFocus();
        txtItemName.requestFocus();
        clearItemFields();
        showHistoryButtons(false);

    }
    
    public void clearItemFields(){

        txtItemName.setText("");
        txtGstAmount.setText("");
        txtGstPercentage.setText("");
        txtHSNCode.setText("");

        txtUnitPrice.setText("");
    }
    
    public void enableFormElements(boolean flag){
        txtHSNCode.setEnabled(flag);
       
    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        if(null == txtHSNCode.getText() || !(txtHSNCode.getText().matches("\\w+"))){
            JOptionPane.showMessageDialog(null, "HSN code "+txtHSNCode.getText() +" is not valid.");
            txtHSNCode.requestFocus();
            return false;
        }
        if(cmbSource.getSelectedItem().toString().equalsIgnoreCase(cmbTarget.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Source and Target cannot be same..!");
            cmbTarget.requestFocus();
            return false;
        }
        if(null == txtItemName.getText() || txtItemName.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Item name "+txtItemName.getText() +" is not valid.");
            txtItemName.requestFocus();
            return false;
        }
        if(null == txtQtyToTransfer.getText() || !(txtQtyToTransfer.getText().matches("\\w+"))){
            JOptionPane.showMessageDialog(null, "Quantity value "+txtQtyToTransfer.getText() +" is not valid.");
            txtQtyToTransfer.requestFocus();
           return false; 
        }
        if(Double.parseDouble(txtQtyToTransfer.getText()) > Double.parseDouble(lblAvailableQty.getText())){
            JOptionPane.showMessageDialog(null, "No sufficient quantity available..!");
            txtQtyToTransfer.requestFocus();
           return false; 
        }
        
        return true;
    }
    
    public void saveStockData(){
 
        Stock stock = new Stock();
        stock.setHsnCode(txtHSNCode.getText());
        stock.setItemName(txtItemName.getText());
       
        //Float fSellingPrice = (Float.parseFloat(txtPurchasePrice.getText()))+(Float.parseFloat(txtMargin.getText()));
        double preMarginSalesPrice = stock.getPurchasePrice()+stock.getPurchasePrice()*stock.getGstPercentage()*0.01;
        stock.setSellingPrice(preMarginSalesPrice+preMarginSalesPrice*stock.getMargin()*0.01);

        StockDAO stockDAO = new StockDAO();
        if (stockIdEdit >0){
            stock.setItemId(stockIdEdit);
            stockDAO.updateStock(stock);
        }else
            stockDAO.insertIntoDB(stock);
        
    }
    
    public final void fetchStockDataIntoTable(Stock stock){
        stockIdEdit=0;
        stockIdEdit = stock.getItemId();
        System.out.println("--Called fetchStockDataIntoTable"+stock.getItemName());
        //initializeForm();
        enableFormElements(true);

    }
    
    public void performItemFieldAction(){
        try{
            StockDAO stockDAO = null;
            //Stock
            stock = null;
            double dUnitGst=0.0;
            double dUnitSellingPrice=0.0;
            double dUnitDiscount=0.0;
            double dUnitPostGstPrice=0.0;

            if(!txtItemName.getText().equalsIgnoreCase(""))
            stockDAO = new StockDAO();
            stock = stockDAO.retrieveByName(txtItemName.getText().trim());
            txtHSNCode.setText(stock.getHsnCode());
            txtUnitPrice.setText(stock.getPurchasePrice()+"");

            //GST Amount Calculation
            txtGstPercentage.setText(stock.getGstPercentage()+"");
            dUnitGst = stock.getGstPercentage()*stock.getPurchasePrice()/100;
            txtGstAmount.setText(df.format(dUnitGst)+"");
            //txt.setText(df.format(dUnitGst)+"");

            //Price after Tax calculation
            dUnitPostGstPrice = dUnitGst +stock.getPurchasePrice();

            //Discount calculation
            if(stock.getDiscount()>0){

            }
            //dUnitDiscount = Double.parseDouble(stock.getDiscount())*Double.parseDouble(stock.getPurchasePrice())/100;

            //Selling Price calculation
            dUnitSellingPrice = dUnitPostGstPrice + dUnitPostGstPrice*stock.getMargin()/100;
            double tempPrice = dUnitSellingPrice;
            dUnitSellingPrice = dUnitSellingPrice * gSalesPercentage *0.01;// *.01 is equivalent to division by 100

            System.out.println("outside cust type loop");


            //txtSellingPrice.setText(df.format(dUnitSellingPrice)+"");
            //Stock Availability Check
            gStockAvailable = stock.getQuantity();
            lblAvailableQty.setText(gStockAvailable+"");
            txtHSNCode.setEnabled(false);
            txtGstPercentage.setEnabled(false);
            txtGstAmount.setEnabled(false);
            txtUnitPrice.setEnabled(false);
            
            List<Double> summaryList = null;
            stockDAO = new StockDAO();
            System.out.println("ITEM ID :" +stock.getItemId());
            summaryList = stockDAO.retrieveAuditSummary(stock.getItemId(), stock.getItemName());
            System.out.println("Summary Size :"+summaryList.size());

            cmdTransfer.requestFocus();
            showHistoryButtons(true);
            txtQtyToTransfer.requestFocus();
        }
        catch(Exception e){
            System.out.println("Error Retrieving the item -"+e.getMessage());
        }
    }
    
    
    public void renderDataIntoTable(List<Supplier> supplierList){

        
    }
    public void showHistoryButtons(boolean choice){

    }
   
    
    public void renderSupplierDataIntoDropDown(List<Supplier> supplierList){
        Supplier supplier = null;
        if(supplierList!= null){
  
        }
    }
    
    public void renderGstDataIntoDropDown(List<GST> gstList){
        GST gst = null;
        if(gstList!= null){

        }  
    }
    
    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cmbSource;
    private javax.swing.JComboBox cmbTarget;
    private javax.swing.JButton cmdTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAvailableQty;
    private javax.swing.JLabel lblQtyTrfr;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JLabel lblUnitPrice2;
    private javax.swing.JLabel lblUnitPrice3;
    private javax.swing.JPanel pnlStockEntry;
    private javax.swing.JTextField txtGstAmount;
    private javax.swing.JTextField txtGstPercentage;
    private javax.swing.JTextField txtHSNCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQtyToTransfer;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
