/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.GstDAO;
import com.essar.dao.ProductCategoryDAO;
import com.essar.dao.VpStockDAO;
import com.essar.dao.SupplierDAO;
import com.essar.pojos.GST;
import com.essar.pojos.ProductCategory;
import com.essar.utils.ConnectionManager;
import com.essar.pojos.Stock;
import com.essar.pojos.Supplier;
import com.essar.utils.QueryStrings;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rahumathulla
 */
public class Vp_StockEntry extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Stock
     */
    long stockIdEdit=0;
    DecimalFormat df = new DecimalFormat("####.##");
    public Vp_StockEntry() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStockEntry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtHSNCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtPurchasePrice = new javax.swing.JTextField();
        txtMargin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        cmbGST = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtReOrderAt = new javax.swing.JTextField();
        btnReports = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        chkAddGst = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSuggestions = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[Stock Entry]");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("HSN Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Commodity/Item Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Re Order at");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("GST %");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Margin");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtHSNCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHSNCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHSNCodeActionPerformed(evt);
            }
        });
        txtHSNCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHSNCodeKeyPressed(evt);
            }
        });

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtItemName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
        });

        txtPurchasePrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPurchasePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPurchasePriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPurchasePriceKeyReleased(evt);
            }
        });

        txtMargin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMargin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMarginKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Category");

        cmbCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Construction", "Others" }));
        cmbCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCategoryKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Purchase Price");

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Description");

        txtDescription.setColumns(10);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescription.setRows(3);
        txtDescription.setTabSize(4);
        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescription);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Supplier Name");

        cmbSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSupplierKeyPressed(evt);
            }
        });

        cmbGST.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbGST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGSTActionPerformed(evt);
            }
        });
        cmbGST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbGSTKeyPressed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("Save");
        btnSave.setAlignmentY(0.0F);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Quantity");

        txtReOrderAt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReOrderAt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReOrderAtKeyPressed(evt);
            }
        });

        btnReports.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnReports.setMnemonic('t');
        btnReports.setText("Stock Report");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setMnemonic('e');
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        btnReset.setMnemonic('R');
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnViewAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewall.png"))); // NOI18N
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        chkAddGst.setText("Add GST ");
        chkAddGst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAddGstActionPerformed(evt);
            }
        });

        txtSuggestions.setEditable(false);
        txtSuggestions.setColumns(10);
        txtSuggestions.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtSuggestions.setRows(5);
        txtSuggestions.setToolTipText("Selling price indicator");
        txtSuggestions.setBorder(null);
        txtSuggestions.setSelectionColor(new java.awt.Color(0, 153, 255));
        jScrollPane2.setViewportView(txtSuggestions);

        javax.swing.GroupLayout pnlStockEntryLayout = new javax.swing.GroupLayout(pnlStockEntry);
        pnlStockEntry.setLayout(pnlStockEntryLayout);
        pnlStockEntryLayout.setHorizontalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewAll))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHSNCode)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbGST, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(chkAddGst)
                                .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                    .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReOrderAt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtQuantity)
                                            .addComponent(txtMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlStockEntryLayout.setVerticalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addComponent(chkAddGst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReOrderAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHSNCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStockEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAddGstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAddGstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAddGstActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        QueryStrings.stockQuery = "SELECT * from stock_vp";
        this.dispose();
        Vp_ViewStockAlerts stockAlerts = new Vp_ViewStockAlerts();
        //stockAlerts.setBounds(40, 40, 940, 500);
        stockAlerts.setVisible(true);
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        initializeForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        ConnectionManager cm = new ConnectionManager();
        Connection con = cm.getConnection();
        //String reportString="D:\\Applications\\Tienda\\reports\\stock_report.jrxml";
        String reportString="src\\com\\essar\\reports\\stock_report_first_choice_vp.jrxml";
        //String reportString="D:\\reports\\users.jrxml";
        JasperReport jr = null;
        try {
            jr = JasperCompileManager.compileReport(reportString);
        } catch (JRException ex) {
            Logger.getLogger(Vp_StockEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jp = null;
        try {
            jp = JasperFillManager.fillReport(jr, null,con);
        } catch (JRException ex) {
            Logger.getLogger(Vp_StockEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JasperViewer.viewReport(jp);
        JasperViewer jv = new JasperViewer(jp, false);
        jv.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt){
                //JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Closed","Why?", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Jasper Window has been closed");
            }
        });
        jv.setVisible(true);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void txtReOrderAtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReOrderAtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnSave.requestFocus();
        }
    }//GEN-LAST:event_txtReOrderAtKeyPressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(btnSave.getText().equalsIgnoreCase("add")){
            ProductCategoryDAO categoryDAO = new ProductCategoryDAO();
            renderCategoryDataIntoDropDown(categoryDAO.retrieveAll());
            
            SupplierDAO supplierDAO = new SupplierDAO();
            renderSupplierDataIntoDropDown(supplierDAO.retrieveAll());

            GstDAO gstDAO = new GstDAO();
            renderGstDataIntoDropDown(gstDAO.retrieveAll());

            btnSave.setText("Save");
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png")));
            txtMargin.setText("5");
            txtReOrderAt.setText("5");
            //chkGstIncluded.setSelected(true);
            enableFormElements(true);
            txtHSNCode.requestFocus();
        }else{
            //Implement Save Logic
            if(validateForm()){
                saveStockData();
                initializeForm();
            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbGSTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbGSTKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            //txtMargin.requestFocus();
            txtPurchasePrice.requestFocus();
        }
    }//GEN-LAST:event_cmbGSTKeyPressed

    private void cmbGSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGSTActionPerformed
        // TODO add your handling code here:
        if(txtSuggestions.isVisible()){
            calculateSuggestions();
        }
    }//GEN-LAST:event_cmbGSTActionPerformed

    private void cmbSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSupplierKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            cmbGST.requestFocus();
        }
    }//GEN-LAST:event_cmbSupplierKeyPressed

    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtPurchasePrice.requestFocus();
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtReOrderAt.requestFocus();
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void cmbCategoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCategoryKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            cmbSupplier.requestFocus();
        }
    }//GEN-LAST:event_cmbCategoryKeyPressed

    private void txtMarginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtQuantity.requestFocus();
        }
    }//GEN-LAST:event_txtMarginKeyPressed

    private void txtPurchasePriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPurchasePriceKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            //cmbGST.requestFocus();
            txtMargin.requestFocus();
            calculateSuggestions();
        }else if(evt.getKeyCode() == KeyEvent.VK_INSERT){
            calculateSuggestions();
        }
            
    }//GEN-LAST:event_txtPurchasePriceKeyPressed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            cmbCategory.requestFocus();
        }
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtHSNCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHSNCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtItemName.requestFocus();
        }
    }//GEN-LAST:event_txtHSNCodeKeyPressed

    private void txtHSNCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHSNCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHSNCodeActionPerformed

    private void txtPurchasePriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPurchasePriceKeyReleased
        // TODO add your handling code here:
        try{
            if(txtSuggestions.isVisible()){
                    calculateSuggestions();
                }
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_txtPurchasePriceKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        Vp_StockFind stockFind = new Vp_StockFind();
        stockFind.setBounds(150, 160, 480, 300);
        stockFind.setVisible(true);
        
       
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vp_StockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vp_StockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vp_StockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vp_StockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vp_StockEntry().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        stockIdEdit =0;
        btnSave.setText("Add");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png")));
        btnSave.requestFocus();
        //txtHSNCode.setText("");
        txtItemName.setText("");
        txtMargin.setText("");
        txtPurchasePrice.setText("");
        txtQuantity.setText("");
        txtReOrderAt.setText("");
        txtDescription.setText("");
        chkAddGst.setSelected(false);
        txtSuggestions.setVisible(false);
        if(cmbCategory.getItemCount()>0){
            cmbCategory.setSelectedIndex(0); 
        }

        cmbSupplier.removeAllItems();
        cmbGST.removeAllItems();
        cmbCategory.removeAllItems();
        


        enableFormElements(false);
        SupplierDAO supplierDAO = new SupplierDAO();
        renderDataIntoTable(supplierDAO.retrieveAll());
        /*mnuCategory = new JPopupMenu();
        mitDelete = new JMenuItem("Delete");
        mitDelete.addActionListener(this);
        
        mnuCategory.add(mitDelete);
         // sets the popup menu for the table
        tblSupplier.setComponentPopupMenu(mnuCategory);      
        tblSupplier.addMouseListener(new TableMouseListener(tblSupplier));*/
   
    }
    
    public void enableFormElements(boolean flag){
        txtHSNCode.setEnabled(flag);
        txtDescription.setEnabled(flag);
        txtItemName.setEnabled(flag);
        txtMargin.setEnabled(flag);
        txtPurchasePrice.setEnabled(flag);
        txtQuantity.setEnabled(flag);
        txtReOrderAt.setEnabled(flag);
        cmbCategory.setEnabled(flag);
        cmbSupplier.setEnabled(flag);
        cmbGST.setEnabled(flag);
    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        if(null == txtHSNCode.getText() || !(txtHSNCode.getText().matches("\\w+"))){
            JOptionPane.showMessageDialog(null, "HSN code "+txtHSNCode.getText() +" is not valid.");
            txtHSNCode.requestFocus();
            return false;
        }
        if(null == txtItemName.getText() || txtItemName.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Item name "+txtItemName.getText() +" is not valid.");
            txtItemName.requestFocus();
            return false;
        }
        
        if(cmbSupplier.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please choose a Supplier Name");
            cmbSupplier.requestFocus();
            return false;
        }
        
        if(cmbGST.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please choose GST value");
            cmbGST.requestFocus();
            return false;
        }
        
        if(null == txtMargin.getText() || !(txtMargin.getText().matches("^\\d*\\.\\d+|\\d+|\\d+\\.\\d*$"))){
            JOptionPane.showMessageDialog(null, "Margin value "+txtMargin.getText() +" is not valid.");
            txtMargin.requestFocus();
            return false;
        }
        
        if(null == txtQuantity.getText() || !(txtQuantity.getText().matches("^\\d*\\.\\d+|\\d+|\\d+\\.\\d*$"))){
            JOptionPane.showMessageDialog(null, "Quantity value "+txtQuantity.getText() +" is not valid.");
            txtQuantity.requestFocus();
            return false;
        }
        
        if(null == txtReOrderAt.getText() || !(txtReOrderAt.getText().matches("^\\d*\\.\\d+|\\d+|\\d+\\.\\d*$"))){
            JOptionPane.showMessageDialog(null, "Re-order value "+txtReOrderAt.getText() +" is not valid.");
            txtReOrderAt.requestFocus();
            return false;
        }
        
        //txtProductCategoryName.setText("");
        return true;
    }
    
    public void saveStockData(){
 
        Stock stock = new Stock();
        stock.setHsnCode(txtHSNCode.getText());
        stock.setItemName(txtItemName.getText());
        stock.setCategory(cmbCategory.getSelectedItem().toString());
        stock.setSupplier(cmbSupplier.getSelectedItem().toString());
        stock.setDescription(txtDescription.getText());
        stock.setPurchasePrice(Double.parseDouble(txtPurchasePrice.getText()));
        stock.setGstPercentage(Double.parseDouble(cmbGST.getSelectedItem().toString()));
        stock.setGstAmount(Double.parseDouble(txtPurchasePrice.getText())*Double.parseDouble(cmbGST.getSelectedItem().toString()));
        stock.setMargin(Double.parseDouble(txtMargin.getText()));
        double dPurchasePrice = 0.0;
        if(chkAddGst.isSelected()){
            dPurchasePrice = Double.parseDouble(txtPurchasePrice.getText())*(1+stock.getGstPercentage()/100); 
            System.out.println("--- Purchase Price : "+ dPurchasePrice);            
            System.out.println("After formatingg --"+df.format(dPurchasePrice));
            stock.setPurchasePrice(Double.parseDouble(df.format(dPurchasePrice)));
        }
        //Float fSellingPrice = (Float.parseFloat(txtPurchasePrice.getText()))+(Float.parseFloat(txtMargin.getText()));
        double preMarginSalesPrice = stock.getPurchasePrice()+stock.getPurchasePrice()*stock.getGstPercentage()*0.01;
        stock.setSellingPrice(preMarginSalesPrice+preMarginSalesPrice*stock.getMargin()*0.01);
        stock.setQuantity(Double.parseDouble(txtQuantity.getText()));
        stock.setReOrderQuantity(Double.parseDouble(txtReOrderAt.getText()));

        VpStockDAO stockDAO = new VpStockDAO();
        if (stockIdEdit >0){
            stock.setItemId(stockIdEdit);
            stockDAO.updateStock(stock);
        }else
            stockDAO.insertIntoDB(stock);
        
    }
    
    public final void fetchStockDataIntoTable(Stock stock){
        stockIdEdit=0;
        stockIdEdit = stock.getItemId();
        System.out.println("--Called fetchStockDataIntoTable"+stock.getItemName());
        //initializeForm();
        enableFormElements(true);
        btnSave.setText("Update");
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png")));
        
        //--!@09/03/2020
        SupplierDAO supplierDAO = new SupplierDAO();
        renderSupplierDataIntoDropDown(supplierDAO.retrieveAll());
        for(int i=0; i<cmbSupplier.getItemCount();i++){
            if(((Supplier)cmbSupplier.getItemAt(i)).getSupplierName().equalsIgnoreCase(stock.getSupplier())){
                cmbSupplier.setSelectedItem(cmbSupplier.getItemAt(i));
            }
        }
        
        //--!@14/06/2020
        ProductCategoryDAO categoryDAO = new ProductCategoryDAO();
        renderCategoryDataIntoDropDown(categoryDAO.retrieveAll());
        for(int i=0; i<cmbCategory.getItemCount();i++){
            if(((ProductCategory)cmbCategory.getItemAt(i)).getProductCategoryName().equalsIgnoreCase(stock.getCategory())){
                cmbCategory.setSelectedItem(cmbCategory.getItemAt(i));
            }
        }
        //cmbSupplier.setSelectedItem(cmbSupplier.getItemAt(3));

        GstDAO gstDAO = new GstDAO();
        renderGstDataIntoDropDown(gstDAO.retrieveAll());
        //cmbGST.setSelectedItem(stock.getGstPercentage());
        for(int i=0; i<cmbGST.getItemCount();i++){
            if(((GST)cmbGST.getItemAt(i)).getGstValue()==stock.getGstPercentage()){
                cmbGST.setSelectedItem(cmbGST.getItemAt(i));
            }
        }
        
        txtHSNCode.setText(stock.getHsnCode());
        txtItemName.setText(stock.getItemName());        
        txtPurchasePrice.setText(stock.getPurchasePrice()+"");
        txtMargin.setText(stock.getMargin()+"");
        txtQuantity.setText(stock.getQuantity()+"");
        txtDescription.setText(stock.getDescription());
        txtReOrderAt.setText(stock.getReOrderQuantity()+"");
        
        
        cmbCategory.setSelectedItem(stock.getCategory());
        
        

        /*if(salesDetailsModel != null){
        salesDetailsModel.addRow(new Object[]{stock.getHsnCode(),stock.getItemName(),stock.getGstPercentage(),df.format(Double.parseDouble(stock.getGstAmount()) * Double.parseDouble(txtQuantity.getText())), itemAmount, Double.parseDouble(txtQuantity.getText()), df.format(itemAmount * Double.parseDouble(txtQuantity.getText())), stock.getItemId()});
        //model.
                
        } */
        //deriveValuesFromSalesInput();
    }
    
    public void renderDataIntoTable(List<Supplier> supplierList){
        /*DefaultTableModel supplierModel = null;
        supplierModel = (DefaultTableModel) tblSupplier.getModel();
        System.out.println("-----"+supplierList.size());
        for(int i=0;i<supplierList.size();i++){
        supplierModel.addRow(new Object[]{supplierList.get(i).getSupplierCode(),supplierList.get(i).getSupplierName(),supplierList.get(i).getSupplierContactNumber(), supplierList.get(i).getSupplierRating(), supplierList.get(i).getSupplierAddress()});
        //model.
        }        */
        
    }
    
    public void calculateSuggestions(){
        txtSuggestions.setVisible(true);
            if(null!= txtPurchasePrice.getText()&& null!= txtMargin.getText()){
                double gstDecimal= ((GST) cmbGST.getSelectedItem()).getGstValue()/100;
                double sp5 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.05;
                double sp8 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.08;
                double sp10 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.10;
                double sp12 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.12;
                double sp15 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.15;
                double sp18 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.18;
                double sp20 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.20;
                double sp25 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.25;
                double sp30 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.30;
                double sp35 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.35;
                double sp40 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.40;
                double sp45 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.45;
                double sp50 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.50;
                double sp55 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.55;
                double sp60 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.60;
                double sp65 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.65;
                double sp70 = (Double.parseDouble(txtPurchasePrice.getText())
                        + Double.parseDouble(txtPurchasePrice.getText())*gstDecimal)*1.70;
                
                txtSuggestions.setText("5%  - "+df.format(sp5)+"\n"+
                                        "8%  - "+df.format(sp8)+"\n"+
                                        "10% - "+df.format(sp10)+"\n"+
                                        "12% - "+df.format(sp12)+"\n"+
                                        "15% - "+df.format(sp15)+"\n"+
                                        "18% - "+df.format(sp18)+"\n"+
                                        "20% - "+df.format(sp20)+"\n"+
                                        "25% - "+df.format(sp25)+"\n"+
                                        "30% - "+df.format(sp30)+"\n"+
                                        "35% - "+df.format(sp35)+"\n"+
                                        "40% - "+df.format(sp40)+"\n"+
                                        "45% - "+df.format(sp45)+"\n"+
                                        "50% - "+df.format(sp50)+"\n"+
                                        "55% - "+df.format(sp55)+"\n"+
                                        "60% - "+df.format(sp60)+"\n"+
                                        "65% - "+df.format(sp65)+"\n"+
                                        "70% - "+df.format(sp70)+"\n"
                                        );
            }
    }
    
    public void renderSupplierDataIntoDropDown(List<Supplier> supplierList){
        Supplier supplier = null;
        cmbSupplier.removeAllItems();
        if(supplierList!= null){
            for(int i=0; i<supplierList.size();i++){
                cmbSupplier.addItem(supplierList.get(i));
            }
            cmbSupplier.setSelectedIndex(0);
            supplier = (Supplier)cmbSupplier.getSelectedItem();            
        }
    }
    
    public void renderGstDataIntoDropDown(List<GST> gstList){
        GST gst = null;
        cmbGST.removeAllItems();
        if(gstList!= null){
            for(int i=0; i<gstList.size();i++){
                cmbGST.addItem(gstList.get(i));
            }
            cmbGST.setSelectedIndex(0);
            gst = (GST)cmbGST.getSelectedItem();            
        }  
    }
    
    public void renderCategoryDataIntoDropDown(List<ProductCategory> categoryList){
        ProductCategory productCategory = null;
        cmbCategory.removeAllItems();
        if(categoryList!= null){
            for(int i=0; i<categoryList.size();i++){
                cmbCategory.addItem(categoryList.get(i));
            }
            cmbCategory.setSelectedIndex(0);
            productCategory = (ProductCategory)cmbCategory.getSelectedItem();            
        }  
    }
    
    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();
           /* if (menu == mitDelete) {
                //int rowIndex = tblSupplier.getSelectedRow();
                System.out.println("--------INSIDE DELETE-"+tblSupplier.getModel().getValueAt(tblSupplier.getSelectedRow(),0));
                String supplierCode = tblSupplier.getModel().getValueAt(tblSupplier.getSelectedRow(),0).toString();
                SupplierDAO supplierDAO = new SupplierDAO();
                supplierDAO.deleteRecordByCode(supplierCode);
                initializeForm();
            } */
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JCheckBox chkAddGst;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbGST;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlStockEntry;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtHSNCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtMargin;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReOrderAt;
    private javax.swing.JTextArea txtSuggestions;
    // End of variables declaration//GEN-END:variables
}
